$ANSIBLE_VAULT;1.1;AES256
36313765646466623337616232663062326663373466353832343039623935633662323438633338
3635393038623961363039303636353762376464656631620a616331333835313134646531636665
65353462343237383838396333626234666465616435393833323937636634306265346237626231
3361356265363337310a653133633061343763616366383736653366353463613837326338363265
65336134326333343765393263366663316635386331663031343439323762363539336432643439
33303732363764373762653164323530353931646435353538316430636337396332613239336462
66393839373737303237646364306561633163643563393066383033303332366261353266303235
61626334376330323964313665393566663133653538643364396463356236346562633630616337
31623932623165636663666331653031656434666230663934323336653436636336616139643863
61366434653863366435666437643531646262653461633633313962363562663039633666616232
39613137386130663934336236333837646138353463626563353835366162613664386535376436
63303338316330636233
